version: '3.8'

services:
  textfission:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: >
      --file /app/input/sample.txt
      --output /app/output/dataset.json
      --format json
      --models gpt-3.5-turbo gpt-4
      --use-parallel
      --temperature 0.7
      --max-tokens 2000
      --chunk-size 1500
      --chunk-overlap 200
      --max-workers 4
      --encoding utf-8
      --indent 2 